-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 16:42:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WebDiP2016x129
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2016x129
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2016x129` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2016x129` ;

-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Područje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Područje` (
  `Podrucje_ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv_Podrucja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Podrucje_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Vozila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Vozila` (
  `Vozilo_ID` INT NOT NULL AUTO_INCREMENT,
  `Marka_Vozila` VARCHAR(45) NOT NULL,
  `Model_Vozila` VARCHAR(45) NOT NULL,
  `Područje_Podrucje_ID` INT NOT NULL,
  PRIMARY KEY (`Vozilo_ID`),
  INDEX `fk_Vozila_Područje1_idx` (`Područje_Podrucje_ID` ASC),
  CONSTRAINT `fk_Vozila_Područje1`
    FOREIGN KEY (`Područje_Podrucje_ID`)
    REFERENCES `WebDiP2016x129`.`Područje` (`Podrucje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Uloga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Uloga` (
  `Uloga_ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv_Uloge` VARCHAR(45) NULL,
  PRIMARY KEY (`Uloga_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Korisnik` (
  `Korisnik_ID` INT NOT NULL AUTO_INCREMENT,
  `Uloga_Uloga_ID` INT NOT NULL,
  `Ime` VARCHAR(45) NULL,
  `Prezime` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Korisnicko_ime` VARCHAR(45) NOT NULL,
  `Lozinka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Korisnik_ID`),
  UNIQUE INDEX `Korisnicko_ime_UNIQUE` (`Korisnicko_ime` ASC),
  INDEX `fk_Korisnik_Uloga_idx` (`Uloga_Uloga_ID` ASC),
  CONSTRAINT `fk_Korisnik_Uloga`
    FOREIGN KEY (`Uloga_Uloga_ID`)
    REFERENCES `WebDiP2016x129`.`Uloga` (`Uloga_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Radi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Radi` (
  `Radi_ID` INT NOT NULL,
  `Područje_Podrucje_ID` INT NOT NULL,
  `Korisnik_Korisnik_ID` INT NOT NULL,
  PRIMARY KEY (`Radi_ID`),
  INDEX `fk_Radi_Područje1_idx` (`Područje_Podrucje_ID` ASC),
  INDEX `fk_Radi_Korisnik1_idx` (`Korisnik_Korisnik_ID` ASC),
  CONSTRAINT `fk_Radi_Područje1`
    FOREIGN KEY (`Područje_Podrucje_ID`)
    REFERENCES `WebDiP2016x129`.`Područje` (`Podrucje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Radi_Korisnik1`
    FOREIGN KEY (`Korisnik_Korisnik_ID`)
    REFERENCES `WebDiP2016x129`.`Korisnik` (`Korisnik_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Ulice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Ulice` (
  `Ulica_ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv_Ulice` VARCHAR(45) NOT NULL,
  `Područje_Podrucje_ID` INT NOT NULL,
  PRIMARY KEY (`Ulica_ID`),
  INDEX `fk_Ulice_Područje1_idx` (`Područje_Podrucje_ID` ASC),
  CONSTRAINT `fk_Ulice_Područje1`
    FOREIGN KEY (`Područje_Podrucje_ID`)
    REFERENCES `WebDiP2016x129`.`Područje` (`Podrucje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Tip_Radnje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Tip_Radnje` (
  `Tip_Radnje_ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tip_Radnje_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Dnevnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Dnevnik` (
  `Dnevnik_ID` INT NOT NULL AUTO_INCREMENT,
  `Tip_Radnje_Tip_Radnje_ID` INT NOT NULL,
  `Korisnik_ID` INT NOT NULL,
  `Vrijeme` TIMESTAMP NOT NULL,
  `Adresa` VARCHAR(45) NULL,
  `Skripta` VARCHAR(45) NULL,
  PRIMARY KEY (`Dnevnik_ID`),
  INDEX `fk_Dnevnik_Tip_Radnje1_idx` (`Tip_Radnje_Tip_Radnje_ID` ASC),
  CONSTRAINT `fk_Dnevnik_Tip_Radnje1`
    FOREIGN KEY (`Tip_Radnje_Tip_Radnje_ID`)
    REFERENCES `WebDiP2016x129`.`Tip_Radnje` (`Tip_Radnje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Odredista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Odredista` (
  `idOdredista` INT NOT NULL AUTO_INCREMENT,
  `Ulica_OD` INT NOT NULL,
  `Ulica_DO` INT NOT NULL,
  PRIMARY KEY (`idOdredista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Oprema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Oprema` (
  `Oprema_ID` INT NOT NULL,
  `Naziv_Opreme` VARCHAR(45) NOT NULL,
  `Područje_Podrucje_ID` INT NOT NULL,
  PRIMARY KEY (`Oprema_ID`),
  INDEX `fk_Oprema_Područje1_idx` (`Područje_Podrucje_ID` ASC),
  CONSTRAINT `fk_Oprema_Područje1`
    FOREIGN KEY (`Područje_Podrucje_ID`)
    REFERENCES `WebDiP2016x129`.`Područje` (`Podrucje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Kuponi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Kuponi` (
  `Kupon_ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `Opis` VARCHAR(45) NOT NULL,
  `Slika` TEXT NOT NULL,
  `Područje_Podrucje_ID` INT NOT NULL,
  PRIMARY KEY (`Kupon_ID`),
  INDEX `fk_Kuponi_Područje1_idx` (`Područje_Podrucje_ID` ASC),
  CONSTRAINT `fk_Kuponi_Područje1`
    FOREIGN KEY (`Područje_Podrucje_ID`)
    REFERENCES `WebDiP2016x129`.`Područje` (`Podrucje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Statistika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Statistika` (
  `Statistika_ID` INT NOT NULL AUTO_INCREMENT,
  `BrojSkupljenihBodova` INT NOT NULL,
  `Korisnik_Korisnik_ID` INT NOT NULL,
  `Datum` DATE NOT NULL,
  `VrijemeOD` TIME NOT NULL,
  `VrijemeDO` TIME NOT NULL,
  PRIMARY KEY (`Statistika_ID`),
  INDEX `fk_Statistika_Korisnik1_idx` (`Korisnik_Korisnik_ID` ASC),
  CONSTRAINT `fk_Statistika_Korisnik1`
    FOREIGN KEY (`Korisnik_Korisnik_ID`)
    REFERENCES `WebDiP2016x129`.`Korisnik` (`Korisnik_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Rezervacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Rezervacija` (
  `Rezervacija_ID` INT NOT NULL AUTO_INCREMENT,
  `Korisnik_ID` INT NOT NULL,
  `Prihvaceno` VARCHAR(2) NULL,
  `Područje_Podrucje_ID` INT NOT NULL,
  `Odredista_idOdredista` INT NOT NULL,
  PRIMARY KEY (`Rezervacija_ID`),
  INDEX `fk_Rezervacija_Područje1_idx` (`Područje_Podrucje_ID` ASC),
  INDEX `fk_Rezervacija_Odredista1_idx` (`Odredista_idOdredista` ASC),
  CONSTRAINT `fk_Rezervacija_Područje1`
    FOREIGN KEY (`Područje_Podrucje_ID`)
    REFERENCES `WebDiP2016x129`.`Područje` (`Podrucje_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezervacija_Odredista1`
    FOREIGN KEY (`Odredista_idOdredista`)
    REFERENCES `WebDiP2016x129`.`Odredista` (`idOdredista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2016x129`.`Račun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2016x129`.`Račun` (
  `Račun_ID` INT NOT NULL AUTO_INCREMENT,
  `Vrijeme` TIME NOT NULL,
  `Datum` DATE NOT NULL,
  `Korisnik` INT NOT NULL,
  `Rezervacija_Rezervacija_ID` INT NOT NULL,
  PRIMARY KEY (`Račun_ID`),
  INDEX `fk_Račun_Rezervacija1_idx` (`Rezervacija_Rezervacija_ID` ASC),
  CONSTRAINT `fk_Račun_Rezervacija1`
    FOREIGN KEY (`Rezervacija_Rezervacija_ID`)
    REFERENCES `WebDiP2016x129`.`Rezervacija` (`Rezervacija_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
